export type Hotel = {
  id: string; name: string; officialName: string; grade: number; gradeDate: string; rooms: number; officialRooms: number; address: string; district: string; zone: string; brand: string; lat: number; lng: number; coordinateConfidence: string; owner: string; assetType: string; dd: string; transaction: null | { amount: number; year: number; buyer: string; theme: string; confidence: string; dd: string; perKey: number };
};

export const hotels: Hotel[] = [
  {
    "id": "SEL-001",
    "name": "풀만 앰배서더 서울 이스트폴",
    "officialName": "풀만 앰배서더 서울 이스트폴",
    "grade": 5,
    "gradeDate": "2026-05-20",
    "rooms": 150,
    "officialRooms": 150,
    "address": "서울 광진구 아차산로 410",
    "district": "광진구",
    "zone": "동서울",
    "brand": "Accor·앰배서더",
    "lat": 37.537089911,
    "lng": 127.08788487,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-002",
    "name": "코리아나호텔",
    "officialName": "코리아나호텔",
    "grade": 4,
    "gradeDate": "2026-05-12",
    "rooms": 285,
    "officialRooms": 285,
    "address": "서울특별시 중구 세종대로 135",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.56810409835,
    "lng": 126.976657606185,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-003",
    "name": "호텔 PJ",
    "officialName": "호텔 PJ",
    "grade": 4,
    "gradeDate": "2026-05-03",
    "rooms": 272,
    "officialRooms": 272,
    "address": "서울특별시 중구 마른내로 71",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.5649895,
    "lng": 126.995671985,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-004",
    "name": "호텔 나루",
    "officialName": "호텔 나루",
    "grade": 5,
    "gradeDate": "2026-04-13",
    "rooms": 196,
    "officialRooms": 196,
    "address": "서울특별시 마포구 마포대로 8",
    "district": "마포구",
    "zone": "서북·홍대",
    "brand": "Accor·앰배서더",
    "lat": 37.537307226,
    "lng": 126.944273178,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-005",
    "name": "콘래드 서울 호텔",
    "officialName": "콘래드 서울 호텔",
    "grade": 5,
    "gradeDate": "2026-04-06",
    "rooms": 434,
    "officialRooms": 434,
    "address": "서울특별시 영등포구 국제금융로 10",
    "district": "영등포구",
    "zone": "YBD",
    "brand": "Hilton",
    "lat": 37.525058436,
    "lng": 126.92593686,
    "coordinateConfidence": "address",
    "transaction": {
      "amount": 4150,
      "year": 2024,
      "buyer": "ARA Korea 운용 부동산펀드",
      "theme": "글로벌 운영형",
      "confidence": "B",
      "dd": "IFC 공용부·HMA·선순위 대출 구조",
      "perKey": 9.56
    },
    "owner": "ARA Korea 운용 부동산펀드",
    "assetType": "복합자산",
    "dd": "IFC 공용부·HMA·선순위 대출 구조"
  },
  {
    "id": "SEL-006",
    "name": "안다즈 서울 강남",
    "officialName": "안다즈 서울 강남",
    "grade": 5,
    "gradeDate": "2026-03-27",
    "rooms": 241,
    "officialRooms": 241,
    "address": "서울특별시 강남구 논현로 854",
    "district": "강남구",
    "zone": "GBD",
    "brand": "Hyatt",
    "lat": 37.525216197,
    "lng": 127.028875628,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-007",
    "name": "메리엇 이그제큐티브 아파트먼트 서울",
    "officialName": "메리엇 이그제큐티브 아파트먼트 서울",
    "grade": 5,
    "gradeDate": "2026-03-21",
    "rooms": 94,
    "officialRooms": 94,
    "address": "서울특별시 영등포구 여의대로8",
    "district": "영등포구",
    "zone": "YBD",
    "brand": "독립·기타",
    "lat": 37.521174175,
    "lng": 126.918554363,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "복합자산",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-008",
    "name": "아난티 앳 강남",
    "officialName": "아난티 앳 강남",
    "grade": 4,
    "gradeDate": "2026-03-04",
    "rooms": 111,
    "officialRooms": 111,
    "address": "서울특별시 강남구 논현로 734",
    "district": "강남구",
    "zone": "GBD",
    "brand": "독립·기타",
    "lat": 37.517551107,
    "lng": 127.029458145,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-009",
    "name": "웨스틴 서울 파르나스",
    "officialName": "웨스틴 서울 파르나스",
    "grade": 5,
    "gradeDate": "2026-02-11",
    "rooms": 564,
    "officialRooms": 656,
    "address": "서울특별시 강남구 봉은사로 524",
    "district": "강남구",
    "zone": "GBD",
    "brand": "Marriott·조선",
    "lat": 37.512953404,
    "lng": 127.057115634,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "파르나스호텔 계열(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-010",
    "name": "더 클래식 500 펜타즈",
    "officialName": "더 클래식 500 펜타즈",
    "grade": 4,
    "gradeDate": "2026-02-06",
    "rooms": 84,
    "officialRooms": 84,
    "address": "서울특별시 광진구 능동로 90",
    "district": "광진구",
    "zone": "동서울",
    "brand": "독립·기타",
    "lat": 37.538359286,
    "lng": 127.070914637,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-011",
    "name": "이비스 스타일 앰배서더 서울 용산",
    "officialName": "(주)서부티엔디 이비스 스타일 앰배서더 서울 용산",
    "grade": 4,
    "gradeDate": "2026-01-22",
    "rooms": 581,
    "officialRooms": 581,
    "address": "서울특별시 용산구 청파로20길 95",
    "district": "용산구",
    "zone": "용산·이태원",
    "brand": "Accor·앰배서더",
    "lat": 37.531891937,
    "lng": 126.962576544,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "멀티브랜드 복합",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-012",
    "name": "프레지던트호텔",
    "officialName": "프레지던트호텔",
    "grade": 4,
    "gradeDate": "2026-01-20",
    "rooms": 271,
    "officialRooms": 271,
    "address": "서울특별시 중구 을지로 16",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.565598068,
    "lng": 126.979406149,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-013",
    "name": "글래드호텔앤리조트(주) 글래드호텔 여의도",
    "officialName": "글래드호텔앤리조트(주) 글래드호텔 여의도 ",
    "grade": 4,
    "gradeDate": "2026-01-14",
    "rooms": 319,
    "officialRooms": 319,
    "address": "서울특별시 영등포구 의사당대로 16",
    "district": "영등포구",
    "zone": "YBD",
    "brand": "GLAD",
    "lat": 37.527413561,
    "lng": 126.917256665,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-014",
    "name": "아만티 호텔 서울",
    "officialName": "아만티 호텔 서울",
    "grade": 4,
    "gradeDate": "2026-01-14",
    "rooms": 150,
    "officialRooms": 150,
    "address": "서울특별시 마포구 월드컵북로 31",
    "district": "마포구",
    "zone": "서북·홍대",
    "brand": "독립·기타",
    "lat": 37.557132062,
    "lng": 126.91870157,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-015",
    "name": "글래드호텔 마포",
    "officialName": "글래드호텔 마포",
    "grade": 4,
    "gradeDate": "2025-12-30",
    "rooms": 378,
    "officialRooms": 378,
    "address": "서울특별시 마포구 마포대로 92",
    "district": "마포구",
    "zone": "서북·홍대",
    "brand": "GLAD",
    "lat": 37.542931058,
    "lng": 126.951246064,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-016",
    "name": "코트야드 메리어트 서울 명동",
    "officialName": "코트야드 메리어트 서울 명동",
    "grade": 4,
    "gradeDate": "2025-12-27",
    "rooms": 400,
    "officialRooms": 400,
    "address": "서울특별시 중구 남대문로 9",
    "district": "중구",
    "zone": "CBD",
    "brand": "Marriott·조선",
    "lat": 37.561190413,
    "lng": 126.976918491,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-017",
    "name": "포시즌스 호텔 서울",
    "officialName": "포시즌스 호텔 서울",
    "grade": 5,
    "gradeDate": "2025-12-18",
    "rooms": 317,
    "officialRooms": 317,
    "address": "서울특별시 종로구 새문안로 97",
    "district": "종로구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.570690249,
    "lng": 126.975395147,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-018",
    "name": "라마다 서울 신도림 호텔",
    "officialName": "라마다 서울 신도림 호텔",
    "grade": 4,
    "gradeDate": "2025-11-10",
    "rooms": 104,
    "officialRooms": 104,
    "address": "서울특별시 구로구 경인로 624",
    "district": "구로구",
    "zone": "서남",
    "brand": "독립·기타",
    "lat": 37.506238849,
    "lng": 126.885391506,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-019",
    "name": "JW메리어트호텔 서울",
    "officialName": "JW메리어트호텔 서울",
    "grade": 5,
    "gradeDate": "2025-10-29",
    "rooms": 379,
    "officialRooms": 379,
    "address": "서울특별시 서초구 신반포로 176",
    "district": "서초구",
    "zone": "GBD",
    "brand": "Marriott·조선",
    "lat": 37.5042813,
    "lng": 127.004566673,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-020",
    "name": "보코서울강남",
    "officialName": "보코서울강남",
    "grade": 4,
    "gradeDate": "2025-10-29",
    "rooms": 151,
    "officialRooms": 151,
    "address": "서울특별시 강남구 도산대로 144",
    "district": "강남구",
    "zone": "GBD",
    "brand": "IHG",
    "lat": 37.517771992,
    "lng": 127.024582577,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-021",
    "name": "힐튼 가든 인 서울 강남",
    "officialName": "힐튼 가든 인 서울 강남 ",
    "grade": 4,
    "gradeDate": "2025-10-16",
    "rooms": 208,
    "officialRooms": 208,
    "address": "서울특별시 서초구 강남대로 253",
    "district": "서초구",
    "zone": "GBD",
    "brand": "Hilton",
    "lat": 37.485941142,
    "lng": 127.032781327,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-022",
    "name": "골든서울호텔",
    "officialName": "골든서울호텔",
    "grade": 4,
    "gradeDate": "2025-10-16",
    "rooms": 260,
    "officialRooms": 260,
    "address": "서울특별시강서구공항대로663",
    "district": "강서구",
    "zone": "마곡·김포공항",
    "brand": "독립·기타",
    "lat": 37.547910136,
    "lng": 126.878116512,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-023",
    "name": "노보텔앰배서더서울동대문호텔",
    "officialName": "노보텔앰배서더서울동대문호텔",
    "grade": 5,
    "gradeDate": "2025-10-16",
    "rooms": 331,
    "officialRooms": 331,
    "address": "서울특별시 중구 을지로 238",
    "district": "중구",
    "zone": "CBD",
    "brand": "Accor·앰배서더",
    "lat": 37.56498463729,
    "lng": 126.978631197904,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-024",
    "name": "메이필드호텔",
    "officialName": "메이필드호텔",
    "grade": 5,
    "gradeDate": "2025-09-30",
    "rooms": 239,
    "officialRooms": 239,
    "address": "서울특별시 강서구 방화대로 94",
    "district": "강서구",
    "zone": "마곡·김포공항",
    "brand": "독립·기타",
    "lat": 37.547512538,
    "lng": 126.819991674,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-025",
    "name": "소피텔 앰배서더 서울",
    "officialName": "소피텔 앰배서더 서울 호텔 앤 서비스드 레지던스(관광호텔)",
    "grade": 5,
    "gradeDate": "2025-09-26",
    "rooms": 403,
    "officialRooms": 403,
    "address": "서울특별시 송파구 잠실로 209",
    "district": "송파구",
    "zone": "GBD",
    "brand": "Accor·앰배서더",
    "lat": 37.513865049,
    "lng": 127.106099956,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "복합자산",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-026",
    "name": "더 링크 서울, 트리뷰트 포트폴리오 호텔",
    "officialName": "더 링크 서울, 트리뷰트 포트폴리오 호텔",
    "grade": 4,
    "gradeDate": "2025-08-25",
    "rooms": 141,
    "officialRooms": 141,
    "address": "서울특별시 구로구 경인로 610",
    "district": "구로구",
    "zone": "서남",
    "brand": "독립·기타",
    "lat": 37.505326177,
    "lng": 126.883810131,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-027",
    "name": "호텔리베라서울",
    "officialName": "호텔리베라서울",
    "grade": 4,
    "gradeDate": "2025-08-23",
    "rooms": 319,
    "officialRooms": 319,
    "address": "서울특별시강남구영동대로737",
    "district": "강남구",
    "zone": "GBD",
    "brand": "독립·기타",
    "lat": 37.52380022,
    "lng": 127.054197151,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-028",
    "name": "포포인츠바이쉐라톤서울강남",
    "officialName": "포포인츠바이쉐라톤서울강남",
    "grade": 4,
    "gradeDate": "2025-07-30",
    "rooms": 199,
    "officialRooms": 199,
    "address": "서울특별시강남구도산대로203",
    "district": "강남구",
    "zone": "GBD",
    "brand": "Marriott·조선",
    "lat": 37.520298132,
    "lng": 127.028513035,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-029",
    "name": "L7 홍대",
    "officialName": "(주)호텔롯데 L7홍대",
    "grade": 4,
    "gradeDate": "2025-06-26",
    "rooms": 340,
    "officialRooms": 340,
    "address": "서울특별시 마포구 양화로 141",
    "district": "마포구",
    "zone": "서북·홍대",
    "brand": "롯데",
    "lat": 37.555753489749,
    "lng": 126.921669471507,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "호텔롯데 계열(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-030",
    "name": "노보텔 앰배서더 서울 용산",
    "officialName": "(주)서부티엔디 노보텔 앰배서더 서울 용산",
    "grade": 5,
    "gradeDate": "2025-06-12",
    "rooms": 621,
    "officialRooms": 621,
    "address": "서울특별시 용산구 청파로20길 95",
    "district": "용산구",
    "zone": "용산·이태원",
    "brand": "Accor·앰배서더",
    "lat": 37.531891937,
    "lng": 126.962576544,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "멀티브랜드 복합",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-031",
    "name": "포포인츠 바이 쉐라톤 조선 서울역",
    "officialName": "(주)조선호텔앤리조트 포포인츠 조선 서울역",
    "grade": 4,
    "gradeDate": "2025-05-31",
    "rooms": 342,
    "officialRooms": 342,
    "address": "서울특별시 용산구 한강대로 366",
    "district": "용산구",
    "zone": "용산·이태원",
    "brand": "Marriott·조선",
    "lat": 37.550605743914,
    "lng": 126.972669580473,
    "coordinateConfidence": "approximate",
    "transaction": {
      "amount": 1720,
      "year": 2025,
      "buyer": "KB자산운용",
      "theme": "Core+ 책임임차",
      "confidence": "B",
      "dd": "2035년 임대차·보증·PIP",
      "perKey": 5.03
    },
    "owner": "KB자산운용",
    "assetType": "단독형",
    "dd": "2035년 임대차·보증·PIP"
  },
  {
    "id": "SEL-032",
    "name": "그랜드 워커힐 서울",
    "officialName": "SK 네트웍스 (주) 워커힐-그랜드 워커힐",
    "grade": 5,
    "gradeDate": "2025-05-30",
    "rooms": 539,
    "officialRooms": 539,
    "address": "서울특별시 광진구 워커힐로 177",
    "district": "광진구",
    "zone": "동서울",
    "brand": "워커힐",
    "lat": 37.552664081,
    "lng": 127.110092806,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "SK네트웍스(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-033",
    "name": "SK 네트웍스 (주) 워커힐 - 비스타 워커힐",
    "officialName": " SK 네트웍스 (주) 워커힐 - 비스타 워커힐",
    "grade": 5,
    "gradeDate": "2025-05-19",
    "rooms": 244,
    "officialRooms": 244,
    "address": "서울특별시 광진구 워커힐로 177",
    "district": "광진구",
    "zone": "동서울",
    "brand": "워커힐",
    "lat": 37.552664081,
    "lng": 127.110092806,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "SK네트웍스(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-034",
    "name": "반얀트리클럽앤스파서울",
    "officialName": "반얀트리클럽앤스파서울",
    "grade": 5,
    "gradeDate": "2025-05-13",
    "rooms": 50,
    "officialRooms": 50,
    "address": "서울특별시 중구 장충단로 60",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.550115637,
    "lng": 127.002254044,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-035",
    "name": "머큐어 서울 마곡",
    "officialName": "머큐어 서울 마곡",
    "grade": 4,
    "gradeDate": "2025-04-18",
    "rooms": 400,
    "officialRooms": 400,
    "address": "서울특별시 강서구 마곡중앙로 143",
    "district": "강서구",
    "zone": "마곡·김포공항",
    "brand": "Accor·앰배서더",
    "lat": 37.565881301447,
    "lng": 126.825656949927,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-036",
    "name": "오크우드 프리미어 코엑스 센터",
    "officialName": "호텔 오크우드 프리미어",
    "grade": 5,
    "gradeDate": "2025-03-26",
    "rooms": 281,
    "officialRooms": 281,
    "address": "서울특별시 강남구 테헤란로87길 46",
    "district": "강남구",
    "zone": "GBD",
    "brand": "독립·기타",
    "lat": 37.510982350219,
    "lng": 127.058205561274,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "복합자산",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-037",
    "name": "L7 강남",
    "officialName": "(주)호텔롯데 L7강남",
    "grade": 4,
    "gradeDate": "2025-02-24",
    "rooms": 333,
    "officialRooms": 333,
    "address": "서울특별시 강남구 테헤란로 415",
    "district": "강남구",
    "zone": "GBD",
    "brand": "롯데",
    "lat": 37.505788587735,
    "lng": 127.051541612973,
    "coordinateConfidence": "approximate",
    "transaction": {
      "amount": 3300,
      "year": 2024,
      "buyer": "롯데리츠",
      "theme": "스폰서 리츠",
      "confidence": "A",
      "dd": "호텔롯데 임대차·복합자산 NOI 배분",
      "perKey": 9.91
    },
    "owner": "롯데리츠",
    "assetType": "복합자산",
    "dd": "호텔롯데 임대차·복합자산 NOI 배분"
  },
  {
    "id": "SEL-038",
    "name": "서울가든호텔",
    "officialName": "(주)서울가든",
    "grade": 4,
    "gradeDate": "2025-02-17",
    "rooms": 372,
    "officialRooms": 372,
    "address": "서울특별시 마포구 마포대로 58",
    "district": "마포구",
    "zone": "서북·홍대",
    "brand": "독립·기타",
    "lat": 37.540663395,
    "lng": 126.948358389,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-039",
    "name": "노보텔 스위트 앰배서더 서울 용산",
    "officialName": "(주)서부티엔디 노보텔 스위트 앰배서더 서울 용산",
    "grade": 5,
    "gradeDate": "2025-01-23",
    "rooms": 264,
    "officialRooms": 264,
    "address": "서울특별시 용산구 청파로20길 95",
    "district": "용산구",
    "zone": "용산·이태원",
    "brand": "Accor·앰배서더",
    "lat": 37.531891937,
    "lng": 126.962576544,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "멀티브랜드 복합",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-040",
    "name": "코트야드 메리어트 서울 보타닉파크",
    "officialName": "코트야드 메리어트 서울 보타닉파크",
    "grade": 4,
    "gradeDate": "2025-01-07",
    "rooms": 261,
    "officialRooms": 261,
    "address": "서울특별시 강서구 마곡중앙12로 10",
    "district": "강서구",
    "zone": "마곡·김포공항",
    "brand": "Marriott·조선",
    "lat": 37.566988281,
    "lng": 126.829503665,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-041",
    "name": "스탠포드호텔 서울",
    "officialName": "스탠포드호텔코리아(주) 스탠포드호텔서울",
    "grade": 4,
    "gradeDate": "2024-12-28",
    "rooms": 239,
    "officialRooms": 239,
    "address": "서울특별시 마포구 월드컵북로58길 15",
    "district": "마포구",
    "zone": "서북·홍대",
    "brand": "독립·기타",
    "lat": 37.582351041,
    "lng": 126.886702431,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-042",
    "name": "레스케이프 호텔",
    "officialName": "(주)조선호텔앤리조트 레스케이프",
    "grade": 4,
    "gradeDate": "2024-12-27",
    "rooms": 204,
    "officialRooms": 204,
    "address": "서울특별시 중구 퇴계로 67",
    "district": "중구",
    "zone": "CBD",
    "brand": "Marriott·조선",
    "lat": 37.560071930084,
    "lng": 126.979573586481,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-043",
    "name": "디에스디엘(주) 프레이저 플레이스 센트럴 서울",
    "officialName": "디에스디엘(주) 프레이저 플레이스 센트럴 서울",
    "grade": 4,
    "gradeDate": "2024-12-27",
    "rooms": 269,
    "officialRooms": 269,
    "address": "서울특별시 중구 통일로 78",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.562592274,
    "lng": 126.969759673,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "복합자산",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-044",
    "name": "voco 서울 명동",
    "officialName": "보코 언 아이에이치지 호텔",
    "grade": 4,
    "gradeDate": "2024-12-20",
    "rooms": 576,
    "officialRooms": 576,
    "address": "서울특별시 중구 퇴계로 52",
    "district": "중구",
    "zone": "CBD",
    "brand": "IHG",
    "lat": 37.558418683502,
    "lng": 126.978544456409,
    "coordinateConfidence": "approximate",
    "transaction": {
      "amount": 2282,
      "year": 2024,
      "buyer": "Gravity AMC·TPG Angelo Gordon 관련",
      "theme": "리포지셔닝",
      "confidence": "C",
      "dd": "브랜드 전환 CAPEX·PIP·안정화 실적",
      "perKey": 3.96
    },
    "owner": "Gravity AMC·TPG Angelo Gordon 관련",
    "assetType": "단독형",
    "dd": "브랜드 전환 CAPEX·PIP·안정화 실적"
  },
  {
    "id": "SEL-045",
    "name": "앰배서더 서울 풀만",
    "officialName": "앰배서더서울풀만호텔",
    "grade": 5,
    "gradeDate": "2024-12-20",
    "rooms": 269,
    "officialRooms": 0,
    "address": "서울특별시 중구 동호로 287",
    "district": "중구",
    "zone": "CBD",
    "brand": "Accor·앰배서더",
    "lat": 37.560140672,
    "lng": 127.002335389,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-046",
    "name": "신라스테이 서초",
    "officialName": "신라스테이 서초",
    "grade": 4,
    "gradeDate": "2024-12-18",
    "rooms": 305,
    "officialRooms": 305,
    "address": "서울특별시 서초구 효령로 427",
    "district": "서초구",
    "zone": "GBD",
    "brand": "신라",
    "lat": 37.489472025,
    "lng": 127.030064762,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-047",
    "name": "그랜드 머큐어 앰배서더 서울 용산",
    "officialName": "(주)서부티엔디 그랜드 머큐어 앰배서더 서울 용산",
    "grade": 5,
    "gradeDate": "2024-12-17",
    "rooms": 201,
    "officialRooms": 201,
    "address": "서울특별시 용산구 청파로20길 95",
    "district": "용산구",
    "zone": "용산·이태원",
    "brand": "Accor·앰배서더",
    "lat": 37.531891937,
    "lng": 126.962576544,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "멀티브랜드 복합",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-048",
    "name": "조선 팰리스 서울 강남",
    "officialName": "(주)조선호텔앤리조트 조선팰리스강남",
    "grade": 5,
    "gradeDate": "2024-12-08",
    "rooms": 254,
    "officialRooms": 254,
    "address": "서울특별시 강남구 테헤란로 231",
    "district": "강남구",
    "zone": "GBD",
    "brand": "Marriott·조선",
    "lat": 37.502881366528,
    "lng": 127.041356594787,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-049",
    "name": "서울신라호텔",
    "officialName": "(주)호텔신라",
    "grade": 5,
    "gradeDate": "2024-11-27",
    "rooms": 464,
    "officialRooms": 464,
    "address": "서울특별시 중구 동호로 249",
    "district": "중구",
    "zone": "CBD",
    "brand": "신라",
    "lat": 37.556105655411,
    "lng": 127.006241952538,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "호텔신라(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-050",
    "name": "몬드리안 서울 이태원",
    "officialName": "몬드리안 서울 이태원 ",
    "grade": 5,
    "gradeDate": "2024-11-03",
    "rooms": 295,
    "officialRooms": 295,
    "address": "서울특별시 용산구 장문로 23",
    "district": "용산구",
    "zone": "용산·이태원",
    "brand": "Accor·앰배서더",
    "lat": 37.528554484,
    "lng": 126.993114607,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-051",
    "name": "알로프트 서울 명동 호텔",
    "officialName": "알로프트 서울 명동 호텔",
    "grade": 4,
    "gradeDate": "2024-09-24",
    "rooms": 223,
    "officialRooms": 223,
    "address": "서울특별시 중구 남대문로 56",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.562277348,
    "lng": 126.981907293,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-052",
    "name": "JW 메리어트 동대문 스퀘어 서울",
    "officialName": "(주)동승 JW메리어트 동대문 스퀘어 서울",
    "grade": 5,
    "gradeDate": "2024-08-23",
    "rooms": 170,
    "officialRooms": 170,
    "address": "서울특별시 종로구 청계천로 279",
    "district": "종로구",
    "zone": "CBD",
    "brand": "Marriott·조선",
    "lat": 37.570448516668,
    "lng": 127.008743782997,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-053",
    "name": "그랜드 인터컨티넨탈 서울 파르나스",
    "officialName": "그랜드 인터컨티넨탈 서울 파르나스",
    "grade": 5,
    "gradeDate": "2024-08-16",
    "rooms": 550,
    "officialRooms": 550,
    "address": "서울특별시 강남구 테헤란로 521",
    "district": "강남구",
    "zone": "GBD",
    "brand": "IHG",
    "lat": 37.509174516,
    "lng": 127.060625245,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "파르나스호텔 계열(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-054",
    "name": "오라카이대학로호텔",
    "officialName": "오라카이대학로호텔",
    "grade": 4,
    "gradeDate": "2024-08-05",
    "rooms": 232,
    "officialRooms": 232,
    "address": "서울특별시 종로구 율곡로 180",
    "district": "종로구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.575530635,
    "lng": 126.998740296,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-055",
    "name": "페어몬트 앰배서더 서울",
    "officialName": "페어몬트 앰배서더 서울",
    "grade": 5,
    "gradeDate": "2024-08-05",
    "rooms": 308,
    "officialRooms": 308,
    "address": "서울특별시 영등포구 여의대로 108",
    "district": "영등포구",
    "zone": "YBD",
    "brand": "독립·기타",
    "lat": 37.527053993,
    "lng": 126.927847603,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "복합자산",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-056",
    "name": "포 포인츠 바이 쉐라톤 조선 명동",
    "officialName": "포 포인츠 바이 쉐라톤 조선 명동",
    "grade": 4,
    "gradeDate": "2024-07-31",
    "rooms": 375,
    "officialRooms": 375,
    "address": "서울특별시 중구 삼일대로10길 36",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.56097,
    "lng": 126.98346,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-057",
    "name": "더 플라자 서울",
    "officialName": "플라자호텔",
    "grade": 5,
    "gradeDate": "2024-07-16",
    "rooms": 306,
    "officialRooms": 306,
    "address": "서울특별시 중구 소공로 119",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.564664165287,
    "lng": 126.978089989618,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-058",
    "name": "롯데호텔 서울",
    "officialName": "호텔롯데",
    "grade": 5,
    "gradeDate": "2024-07-16",
    "rooms": 1015,
    "officialRooms": 1015,
    "address": "서울특별시 중구 을지로 30",
    "district": "중구",
    "zone": "CBD",
    "brand": "롯데",
    "lat": 37.565345907381,
    "lng": 126.981007562476,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "호텔롯데 계열(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-059",
    "name": "코트야드 바이 메리어트 서울 타임스퀘어",
    "officialName": "코트야드 바이 메리어트 서울 타임스퀘어",
    "grade": 4,
    "gradeDate": "2024-07-07",
    "rooms": 283,
    "officialRooms": 283,
    "address": "서울특별시 영등포구 영중로 15",
    "district": "영등포구",
    "zone": "YBD",
    "brand": "Marriott·조선",
    "lat": 37.516874721,
    "lng": 126.904378098,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "복합자산",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-060",
    "name": "호텔롯데 롯데호텔월드",
    "officialName": "호텔롯데 롯데호텔월드",
    "grade": 5,
    "gradeDate": "2024-07-07",
    "rooms": 477,
    "officialRooms": 477,
    "address": "서울특별시 송파구 올림픽로 240",
    "district": "송파구",
    "zone": "GBD",
    "brand": "롯데",
    "lat": 37.511481834,
    "lng": 127.098224127,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "호텔롯데 계열(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-061",
    "name": "웨스틴 조선 서울",
    "officialName": "(주)조선호텔앤리조트",
    "grade": 5,
    "gradeDate": "2024-05-20",
    "rooms": 462,
    "officialRooms": 462,
    "address": "서울특별시 중구 소공로 106",
    "district": "중구",
    "zone": "CBD",
    "brand": "Marriott·조선",
    "lat": 37.564484122006,
    "lng": 126.980184459584,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-062",
    "name": "호텔 인 나인",
    "officialName": "호텔 인 나인",
    "grade": 4,
    "gradeDate": "2024-05-10",
    "rooms": 152,
    "officialRooms": 152,
    "address": "서울특별시 강남구 영동대로 618",
    "district": "강남구",
    "zone": "GBD",
    "brand": "독립·기타",
    "lat": 37.515532296,
    "lng": 127.060061555,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-063",
    "name": "퍼시픽호텔",
    "officialName": "퍼시픽호텔",
    "grade": 4,
    "gradeDate": "2024-04-17",
    "rooms": 181,
    "officialRooms": 181,
    "address": "서울특별시 중구 퇴계로20길 2",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.559665589,
    "lng": 126.985421476,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-064",
    "name": "신라스테이삼성",
    "officialName": "신라스테이삼성",
    "grade": 4,
    "gradeDate": "2024-04-04",
    "rooms": 309,
    "officialRooms": 309,
    "address": "서울특별시 강남구 영동대로 506",
    "district": "강남구",
    "zone": "GBD",
    "brand": "신라",
    "lat": 37.509905063,
    "lng": 127.063177079,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-065",
    "name": "오라카이 인사동 스위츠",
    "officialName": "오라카이 인사동 스위츠",
    "grade": 4,
    "gradeDate": "2024-01-04",
    "rooms": 213,
    "officialRooms": 213,
    "address": "서울특별시 종로구 인사동4길 18",
    "district": "종로구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.573062089,
    "lng": 126.987334039,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-066",
    "name": "아미드호텔",
    "officialName": "아미드호텔",
    "grade": 4,
    "gradeDate": "2024-01-03",
    "rooms": 250,
    "officialRooms": 250,
    "address": "서울특별시 종로구 인사동5길 38",
    "district": "종로구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.572584099869,
    "lng": 126.984210790593,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-067",
    "name": "스위스그랜드호텔서울",
    "officialName": "스위스그랜드호텔서울",
    "grade": 4,
    "gradeDate": "2023-12-08",
    "rooms": 396,
    "officialRooms": 396,
    "address": "서울특별시 서대문구 연희로 353",
    "district": "서대문구",
    "zone": "서북·홍대",
    "brand": "독립·기타",
    "lat": 37.590049755,
    "lng": 126.934775654,
    "coordinateConfidence": "approximate",
    "transaction": {
      "amount": 3208,
      "year": 2025,
      "buyer": "홍제353PFV 관련",
      "theme": "개발형",
      "confidence": "C",
      "dd": "인허가·명도·호텔 존치가치 비교",
      "perKey": 8.1
    },
    "owner": "홍제353PFV 관련",
    "assetType": "단독형",
    "dd": "인허가·명도·호텔 존치가치 비교"
  },
  {
    "id": "SEL-068",
    "name": "파크하얏트서울",
    "officialName": "파크하얏트서울",
    "grade": 5,
    "gradeDate": "2023-11-27",
    "rooms": 185,
    "officialRooms": 185,
    "address": "서울특별시 강남구 테헤란로 606",
    "district": "강남구",
    "zone": "GBD",
    "brand": "Hyatt",
    "lat": 37.508733653235,
    "lng": 127.064281770524,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-069",
    "name": "프레이저플레이스남대문",
    "officialName": "프레이저플레이스남대문",
    "grade": 4,
    "gradeDate": "2023-10-20",
    "rooms": 252,
    "officialRooms": 252,
    "address": "서울특별시 중구 세종대로 58",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.561312145,
    "lng": 126.976471423,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "복합자산",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-070",
    "name": "삼정관광호텔",
    "officialName": "삼정관광호텔",
    "grade": 4,
    "gradeDate": "2023-09-22",
    "rooms": 160,
    "officialRooms": 160,
    "address": "서울특별시 강남구 봉은사로 150",
    "district": "강남구",
    "zone": "GBD",
    "brand": "독립·기타",
    "lat": 37.505920577,
    "lng": 127.031156787,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-071",
    "name": "나인트리 프리미어 로카우스호텔 서울 용산",
    "officialName": "나인트리 프리미어 로카우스호텔 서울 용산",
    "grade": 4,
    "gradeDate": "2023-09-14",
    "rooms": 274,
    "officialRooms": 274,
    "address": "서울특별시 용산구 한강대로23길 25",
    "district": "용산구",
    "zone": "용산·이태원",
    "brand": "독립·기타",
    "lat": 37.5368,
    "lng": 126.98756,
    "coordinateConfidence": "district",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-072",
    "name": "시그니엘서울",
    "officialName": "시그니엘서울",
    "grade": 5,
    "gradeDate": "2023-08-16",
    "rooms": 235,
    "officialRooms": 235,
    "address": "서울특별시 송파구 올림픽로 300",
    "district": "송파구",
    "zone": "GBD",
    "brand": "롯데",
    "lat": 37.512836069,
    "lng": 127.101711815,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "호텔롯데 계열(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-073",
    "name": "로얄호텔서울",
    "officialName": "로얄호텔서울",
    "grade": 4,
    "gradeDate": "2023-08-08",
    "rooms": 310,
    "officialRooms": 310,
    "address": "서울특별시 중구 명동길 61",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.56438702,
    "lng": 126.985864148,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-074",
    "name": "오라카이 청계산 호텔",
    "officialName": "금보개발(주) 오라카이 청계산 호텔",
    "grade": 4,
    "gradeDate": "2023-07-21",
    "rooms": 193,
    "officialRooms": 193,
    "address": "서울특별시 서초구 청계산로9길 1-7",
    "district": "서초구",
    "zone": "GBD",
    "brand": "독립·기타",
    "lat": 37.449172653,
    "lng": 127.05452712,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-075",
    "name": "켄싱턴호텔 여의도",
    "officialName": "켄싱턴호텔 여의도",
    "grade": 4,
    "gradeDate": "2023-07-10",
    "rooms": 201,
    "officialRooms": 201,
    "address": "서울특별시 영등포구 국회대로76길 16",
    "district": "영등포구",
    "zone": "YBD",
    "brand": "독립·기타",
    "lat": 37.530290356,
    "lng": 126.921962988,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-076",
    "name": "포포인츠바이쉐라톤서울구로",
    "officialName": "포포인츠바이쉐라톤서울구로",
    "grade": 4,
    "gradeDate": "2023-07-10",
    "rooms": 202,
    "officialRooms": 202,
    "address": "서울특별시 구로구 디지털로32길 72",
    "district": "구로구",
    "zone": "서남",
    "brand": "Marriott·조선",
    "lat": 37.4941,
    "lng": 126.88868,
    "coordinateConfidence": "district",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-077",
    "name": "호텔 스카이파크 킹스타운 동대문",
    "officialName": "호텔스카이파크 킹스타운동대문지점",
    "grade": 4,
    "gradeDate": "2023-07-07",
    "rooms": 406,
    "officialRooms": 406,
    "address": "서울특별시 중구 장충단로13길 20",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.568707677,
    "lng": 127.007653116,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-078",
    "name": "AC호텔 바이 메리어트 서울 강남",
    "officialName": " AC호텔 바이 메리어트 서울 강남",
    "grade": 4,
    "gradeDate": "2023-07-06",
    "rooms": 274,
    "officialRooms": 274,
    "address": "서울특별시 강남구 테헤란로25길 10",
    "district": "강남구",
    "zone": "GBD",
    "brand": "Marriott·조선",
    "lat": 37.501230063,
    "lng": 127.035431576,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-079",
    "name": "L7 명동",
    "officialName": "㈜호텔롯데 L7명동",
    "grade": 4,
    "gradeDate": "2023-06-14",
    "rooms": 251,
    "officialRooms": 251,
    "address": "서울특별시 중구 퇴계로 137",
    "district": "중구",
    "zone": "CBD",
    "brand": "롯데",
    "lat": 37.561405574699,
    "lng": 126.98697606427,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "호텔롯데 계열(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-080",
    "name": "머큐어 앰배서더 서울 홍대",
    "officialName": "머큐어 앰배서더 서울 홍대",
    "grade": 4,
    "gradeDate": "2023-06-07",
    "rooms": 270,
    "officialRooms": 270,
    "address": "서울특별시 마포구 양화로 144",
    "district": "마포구",
    "zone": "서북·홍대",
    "brand": "Accor·앰배서더",
    "lat": 37.555354666,
    "lng": 126.922345351,
    "coordinateConfidence": "address",
    "transaction": {
      "amount": 2620,
      "year": 2025,
      "buyer": "Goldman Sachs 주요 투자 구조",
      "theme": "복합 Value-add",
      "confidence": "B",
      "dd": "호텔 운영계약·무신사 임대차·대출",
      "perKey": 9.7
    },
    "owner": "Goldman Sachs 주요 투자 구조",
    "assetType": "복합자산",
    "dd": "호텔 운영계약·무신사 임대차·대출"
  },
  {
    "id": "SEL-081",
    "name": "소테츠호텔즈 더스프라지르 서울 명동",
    "officialName": "소테츠호텔즈 더스프라지르 서울 명동",
    "grade": 4,
    "gradeDate": "2023-06-02",
    "rooms": 428,
    "officialRooms": 428,
    "address": "서울특별시 중구 남대문로5길 15",
    "district": "중구",
    "zone": "CBD",
    "brand": "독립·기타",
    "lat": 37.561997381,
    "lng": 126.978756933,
    "coordinateConfidence": "address",
    "transaction": null,
    "owner": "미확인(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  },
  {
    "id": "SEL-082",
    "name": "롯데시티호텔 명동",
    "officialName": "㈜호텔롯데 롯데시티호텔 명동",
    "grade": 4,
    "gradeDate": "2023-06-02",
    "rooms": 435,
    "officialRooms": 435,
    "address": "서울특별시 중구 삼일대로 362",
    "district": "중구",
    "zone": "CBD",
    "brand": "롯데",
    "lat": 37.566948694907,
    "lng": 126.988088175183,
    "coordinateConfidence": "approximate",
    "transaction": null,
    "owner": "호텔롯데 계열(등기 확인 필요)",
    "assetType": "단독형",
    "dd": "등기·운영계약·최근 CAPEX·NOI 확보"
  }
];
